spring:
  config:
    import: consul:consul-server:8500
  cloud:
    consul:
      config:
        enabled: true
        format: yaml
        prefixes: config
  profiles:
    active: dev

server:
  port: 8080